import { useState } from 'react';
import PublicLayout from '../../../Components/Layout/PublicLayout';
import Container from '../../../Components/UI/Container';
import SeoHead from '../../../Components/SEO/SeoHead';
import LeadForm from '../../../Components/RealEstate/LeadForm';
import { galleryMedia } from '../../../Components/RealEstate/DetailSections';

const money = (value) => value ? new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(Number(value)) : null;
const formatNumber = (value) => Number(value).toLocaleString('pt-BR', { maximumFractionDigits: 2 });
const present = (value) => value !== null && value !== undefined && value !== '' && Number(value) !== 0;
const whatsappUrl = (item, fallback) => { const phone = String(item.whatsapp_contact || fallback || '').replace(/\D/g, ''); return phone ? `https://wa.me/${phone}?text=${encodeURIComponent(`Olá, tenho interesse no imóvel ${item.title}.`)}` : null; };

function PropertyGallery({ items }) {
    const [start, setStart] = useState(0);
    if (!items.length) return null;
    const visible = [0, 1, 2].map((offset) => items[(start + offset) % items.length]).filter((item, index, list) => item && list.indexOf(item) === index);
    const move = (direction) => setStart((current) => (current + direction + items.length) % items.length);
    return <section className="relative overflow-hidden bg-ink pt-[76px]" aria-label="Galeria do imóvel"><div className="grid h-[340px] gap-1 tablet:h-[470px] tablet:grid-cols-2 desktop:h-[520px] desktop:grid-cols-3">{visible.map((media, index) => { const video = media.type === 'video' || media.mime_type?.startsWith('video/'); return <div key={media.id || index} className={`${index > 0 ? 'hidden tablet:block' : ''} ${index > 1 ? 'tablet:hidden desktop:block' : ''}`}>{video ? <video src={media.url} poster={media.poster_url || undefined} controls playsInline preload="metadata" className="h-full w-full object-cover" /> : <img src={media.url} alt={media.alt_text || ''} className="h-full w-full object-cover" />}</div>; })}</div>{items.length > 1 && <><button type="button" onClick={() => move(-1)} aria-label="Mídia anterior" className="absolute bottom-5 right-20 grid size-11 place-items-center rounded-md bg-brand text-2xl text-white">&#8249;</button><button type="button" onClick={() => move(1)} aria-label="Próxima mídia" className="absolute bottom-5 right-5 grid size-11 place-items-center rounded-md bg-brand text-2xl text-white">&#8250;</button></>}</section>;
}

const InfoCell = ({ label, value }) => present(value) ? <div className="rounded-xl border border-line px-4 py-3"><span className="block text-xs uppercase text-muted">{label}</span><strong className="mt-1 block font-medium text-brand">{value}</strong></div> : null;
const Row = ({ label, value }) => value ? <div className="flex items-center justify-between gap-4 rounded-xl border border-line px-4 py-3"><span className="text-xs uppercase text-muted">{label}</span><strong className="text-sm font-medium text-ink">{value}</strong></div> : null;

export default function Show({ item, globalWhatsapp }) {
    const gallery = galleryMedia(item);
    const address = [item.address, item.address_number, item.neighborhood, item.city?.name, item.city?.state?.code, item.postal_code].filter(Boolean).join(', ');
    const facts = [['Quartos', item.bedrooms], ['Suítes', item.suites], ['Banheiros', item.bathrooms], ['Lavabos', item.lavatories], ['Vagas', item.parking_spaces], ['Área total', present(item.total_area) ? `${formatNumber(item.total_area)} m²` : null]];
    const conditions = [['Aceita permuta', item.accepts_exchange], ['Aceita financiamento', item.accepts_financing], ['Mobiliado', item.furnished], ['Imóvel novo', item.is_new]];
    const areas = [['Área total', item.total_area], ['Área útil', item.usable_area], ['Área construída', item.built_area], ['Área do terreno', item.land_area]].filter(([, value]) => present(value));
    const plans = (item.floor_plans || []).filter((plan) => plan.is_active !== false && (plan.external_url || plan.media_asset?.url));
    const whatsapp = whatsappUrl(item, globalWhatsapp);
    const currentPrice = item.sale_price || item.regular_price || item.rent_price;
    return <PublicLayout><SeoHead title={item.seo?.title || item.title} description={item.seo?.description || item.excerpt} /><PropertyGallery items={gallery} /><section className="bg-surface py-10 tablet:py-14"><Container className="grid max-w-[1120px] gap-6 desktop:grid-cols-[minmax(0,1.85fr)_minmax(310px,1fr)] desktop:items-start"><main className="space-y-5">
        <article className="rounded-2xl bg-white p-6 shadow-card tablet:p-8"><p className="text-sm uppercase text-muted">{item.business_type?.name || 'Imóvel'}</p><h1 className="mt-2 text-3xl font-normal leading-tight tablet:text-4xl">{item.title}</h1>{address && <p className="mt-2 text-base text-muted">{address}</p>}{(item.condominium?.title || item.condominium_name) && <p className="mt-1 text-sm text-muted">{item.condominium?.title || item.condominium_name}</p>}<div className="mt-6 grid grid-cols-2 gap-3 tablet:grid-cols-3">{facts.map(([label, value]) => <InfoCell key={label} label={label} value={value} />)}</div></article>
        {(item.description || item.excerpt) && <article className="rounded-2xl bg-white p-6 shadow-card tablet:p-8"><h2 className="text-2xl font-normal">Descrição do Imóvel</h2><div className="mt-5 max-w-none whitespace-pre-line font-light leading-7 text-muted" dangerouslySetInnerHTML={{ __html: item.description || item.excerpt }} /></article>}
        {conditions.some(([, value]) => value) && <article className="rounded-2xl bg-white p-6 shadow-card tablet:p-8"><h2 className="text-2xl font-normal">Condições Comerciais</h2><div className="mt-5 grid gap-3 tablet:grid-cols-2">{conditions.map(([label, value]) => <Row key={label} label={label} value={value ? 'Sim' : 'Não'} />)}</div></article>}
        {areas.length > 0 && <article className="rounded-2xl bg-white p-6 shadow-card tablet:p-8"><h2 className="text-2xl font-normal">Áreas</h2><div className="mt-5 grid gap-3 tablet:grid-cols-2">{areas.map(([label, value]) => <Row key={label} label={label} value={`${formatNumber(value)} m²`} />)}</div></article>}
        {plans.length > 0 && <article className="rounded-2xl bg-white p-6 shadow-card tablet:p-8"><h2 className="text-2xl font-normal">Planta do imóvel</h2><p className="mt-3 max-w-xl text-sm leading-6 text-muted">{item.floor_plans_support_text || 'Faça o download da planta e tenha acesso aos detalhes do imóvel, incluindo a distribuição dos ambientes, medidas e organização do projeto.'}</p><div className="mt-5 flex flex-wrap gap-3">{plans.map((plan) => <a key={plan.id} href={plan.external_url || plan.media_asset.url} target="_blank" rel="noreferrer" className="brand-button">{plans.length === 1 ? 'Baixe a planta completa aqui' : plan.name}</a>)}</div></article>}
        <a href="/imoveis" className="brand-button inline-flex">&#8592; Voltar</a>
    </main><aside className="space-y-4 desktop:sticky desktop:top-24"><div className="rounded-2xl bg-white p-6 shadow-card"><div className="flex flex-wrap gap-2 text-[.65rem] uppercase"><span className="rounded-md bg-brand px-3 py-1.5 text-white">{item.property_type?.name || 'Imóvel'}</span>{item.development_status?.name && <span className="rounded-md bg-surface px-3 py-1.5">{item.development_status.name}</span>}</div><div className="mt-4 rounded-xl border border-line p-4">{item.regular_price && item.sale_price && Number(item.regular_price) !== Number(item.sale_price) && <p className="text-lg text-muted line-through">{money(item.regular_price)}</p>}<span className="mt-2 block text-xs font-medium uppercase">{item.price_on_request || !currentPrice ? 'Valor' : 'Por apenas:'}</span><strong className="mt-1 block text-3xl font-medium text-brand">{item.price_on_request || !currentPrice ? 'Sob consulta' : money(currentPrice)}</strong></div><div className="mt-4 space-y-2 border-t border-line pt-4"><Row label="Condomínio" value={money(item.condominium_fee)} /><Row label="IPTU" value={money(item.iptu)} /></div></div><LeadForm entityType="property" entityId={item.id} title="Tenho interesse" />{whatsapp && <a href={whatsapp} target="_blank" rel="noreferrer" className="brand-button flex w-full justify-center">Falar no WhatsApp</a>}</aside></Container></section></PublicLayout>;
}
