import Field from '../Forms/Field';

const blank = { product_name: '', title: '', text: '', original_price: '', promotional_price: '', button_text: '', button_url: '', media_asset_id: '', image: null, is_active: true };

export default function CondominiumPromotions({ rows = [], onChange }) {
    const update = (index, key, value) => onChange(rows.map((row, rowIndex) => rowIndex === index ? { ...row, [key]: value } : row));
    const move = (index, direction) => { const next = index + direction; if (next < 0 || next >= rows.length) return; const copy = [...rows]; [copy[index], copy[next]] = [copy[next], copy[index]]; onChange(copy); };
    return <section className="rounded-card bg-white p-6 shadow-card"><div className="mb-6 flex flex-wrap items-center justify-between gap-4"><div><h2 className="text-lg font-medium text-ink">Promoções</h2><p className="mt-1 text-sm text-muted">A seção só aparece quando existir ao menos uma promoção ativa.</p></div><button type="button" onClick={() => onChange([...rows, { ...blank }])} className="rounded-lg border border-brand px-4 py-2 text-xs font-medium uppercase text-brand">Adicionar promoção</button></div><div className="space-y-5">{rows.map((row, index) => <article key={row.id || index} className="rounded-xl bg-surface p-5"><div className="mb-4 flex justify-between text-xs uppercase text-muted"><span>Promoção {index + 1}</span><div className="flex gap-3"><button type="button" disabled={index === 0} onClick={() => move(index, -1)}>Subir</button><button type="button" disabled={index === rows.length - 1} onClick={() => move(index, 1)}>Descer</button><button type="button" className="text-red-700" onClick={() => onChange(rows.filter((_, rowIndex) => rowIndex !== index))}>Remover</button></div></div><div className="grid gap-4 tablet:grid-cols-2"><Field label="Nome do produto promovido" value={row.product_name || ''} onChange={(e) => update(index, 'product_name', e.target.value)} /><Field label="Título da promoção" value={row.title || ''} onChange={(e) => update(index, 'title', e.target.value)} /><Field label="Texto" as="textarea" value={row.text || ''} onChange={(e) => update(index, 'text', e.target.value)} /><div className="grid gap-4 tablet:grid-cols-2"><Field label="Preço original" type="number" step="0.01" value={row.original_price || ''} onChange={(e) => update(index, 'original_price', e.target.value)} /><Field label="Preço promocional" type="number" step="0.01" value={row.promotional_price || ''} onChange={(e) => update(index, 'promotional_price', e.target.value)} /></div><Field label="Texto do botão" value={row.button_text || ''} onChange={(e) => update(index, 'button_text', e.target.value)} /><Field label="Link do botão" type="url" value={row.button_url || ''} onChange={(e) => update(index, 'button_url', e.target.value)} /><label><span className="admin-label">Imagem</span>{row.media_asset?.url && <img src={row.media_asset.url} alt="" className="mb-2 aspect-video w-full rounded-lg object-cover" />}<input className="admin-input" type="file" accept="image/jpeg,image/png,image/webp,.heic,.heif" onChange={(e) => update(index, 'image', e.target.files?.[0] || null)} /></label><label className="flex items-center gap-2"><input type="checkbox" checked={row.is_active !== false} onChange={(e) => update(index, 'is_active', e.target.checked)} /> Promoção ativa</label></div></article>)}</div></section>;
}
