import Field from '../Forms/Field';
import Button from '../UI/Button';
import SortableCollection from './SortableCollection';

const blank = { product_name: '', title: '', text: '', original_price: '', promotional_price: '', button_text: '', button_url: '', media_asset_id: '', image: null, is_active: true };

export default function PromotionManager({ rows = [], onChange }) {
    const update = (index, key, value) => onChange(rows.map((row, rowIndex) => rowIndex === index ? { ...row, [key]: value } : row));
    return <section className="rounded-card bg-white p-6 shadow-card">
        <div className="mb-6 flex flex-wrap items-center justify-between gap-4"><div><h2 className="text-lg font-medium text-ink">Promo&ccedil;&otilde;es</h2><p className="mt-1 text-sm text-muted">Arraste os cards para definir a ordem do carrossel p&uacute;blico.</p></div><Button type="button" onClick={() => onChange([...rows, { ...blank, _key: crypto.randomUUID() }])}>Adicionar promo&ccedil;&atilde;o</Button></div>
        <SortableCollection items={rows} onChange={onChange} getKey={(row, index) => row.id || row._key || `existing-${index}`} label="promo\u00e7\u00e3o" onRemove={(_, index) => onChange(rows.filter((__, rowIndex) => rowIndex !== index))} renderItem={(row, index) => <div className="grid gap-4 bg-surface p-5 tablet:grid-cols-2"><Field label="Nome do produto promovido" value={row.product_name || ''} onChange={(event) => update(index, 'product_name', event.target.value)} /><Field label={'T\u00edtulo da promo\u00e7\u00e3o'} value={row.title || ''} onChange={(event) => update(index, 'title', event.target.value)} /><Field label="Texto" as="textarea" value={row.text || ''} onChange={(event) => update(index, 'text', event.target.value)} /><div className="grid gap-4 tablet:grid-cols-2"><Field label={'Pre\u00e7o original'} type="number" step="0.01" value={row.original_price || ''} onChange={(event) => update(index, 'original_price', event.target.value)} /><Field label={'Pre\u00e7o promocional'} type="number" step="0.01" value={row.promotional_price || ''} onChange={(event) => update(index, 'promotional_price', event.target.value)} /></div><Field label={'Texto do bot\u00e3o'} value={row.button_text || ''} onChange={(event) => update(index, 'button_text', event.target.value)} /><Field label={'Link do bot\u00e3o'} type="url" value={row.button_url || ''} onChange={(event) => update(index, 'button_url', event.target.value)} /><label><span className="admin-label">Imagem</span>{row.media_asset?.url && <img src={row.media_asset.url} alt="" className="mb-2 aspect-[4/3] w-40 rounded-lg object-cover" />}<input className="admin-input" type="file" accept="image/jpeg,image/png,image/webp,.heic,.heif" onChange={(event) => update(index, 'image', event.target.files?.[0] || null)} /></label><label className="flex items-center gap-2"><input type="checkbox" checked={row.is_active !== false} onChange={(event) => update(index, 'is_active', event.target.checked)} /> Promo&ccedil;&atilde;o ativa</label></div>} />
    </section>;
}
