import Field from '../Forms/Field';
import OverallProgressBar from '../RealEstate/OverallProgressBar';

const blankPlan = { name: '', description: '', area: '', bedrooms: '', suites: '', bathrooms: '', parking_spaces: '', external_url: '', media_asset_id: '' };
const normalize = (value = '') => value.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase().replace(/[^a-z0-9]/g, '');

export const fixedStageDefaults = (item, definitions = []) => definitions.map((definition) => {
    const candidates = [definition.name, ...(definition.aliases || [])].map(normalize);
    const existing = item?.construction_stages?.find((stage) => stage.code === definition.code || candidates.includes(normalize(stage.name)));
    return { id: existing?.id, code: definition.code, name: definition.name, progress_percent: existing?.progress_percent ?? '' };
});

function Repeater({ title, rows, onChange, blank, render }) {
    const update = (index, key, value) => onChange(rows.map((row, rowIndex) => rowIndex === index ? { ...row, [key]: value } : row));
    const move = (index, direction) => { const next = index + direction; if (next < 0 || next >= rows.length) return; const copy = [...rows]; [copy[index], copy[next]] = [copy[next], copy[index]]; onChange(copy); };
    return <section className="rounded-xl border border-line bg-white p-6 shadow-sm"><div className="mb-5 flex flex-wrap items-center justify-between gap-4"><div><h2 className="text-lg font-medium text-ink">{title}</h2><p className="mt-1 text-sm text-muted">Os itens são exibidos no site na ordem abaixo.</p></div><button type="button" onClick={() => onChange([...rows, { ...blank }])} className="rounded-lg border border-brand px-4 py-2 text-xs font-medium uppercase text-brand">Adicionar</button></div><div className="space-y-4">{rows.map((row, index) => <div key={row.id || index} className="rounded-xl bg-surface p-4"><div className="mb-3 flex items-center justify-between text-xs font-medium uppercase text-muted"><span>Item {index + 1}</span><div className="flex gap-3"><button type="button" disabled={index === 0} onClick={() => move(index, -1)}>Subir</button><button type="button" disabled={index === rows.length - 1} onClick={() => move(index, 1)}>Descer</button><button type="button" onClick={() => onChange(rows.filter((_, rowIndex) => rowIndex !== index))} className="text-red-700">Remover</button></div></div>{render(row, index, update)}</div>)}</div></section>;
}

function ConstructionStageGrid({ data, setData }) {
    const stages = data.construction_stages || [];
    const filled = stages.filter((stage) => stage.progress_percent !== '' && stage.progress_percent != null);
    const overall = filled.length ? Math.round(filled.reduce((total, stage) => total + Math.max(0, Math.min(100, Number(stage.progress_percent) || 0)), 0) / filled.length) : null;
    return <section className="rounded-xl border border-line bg-white p-6 shadow-sm"><div className="mb-6"><h2 className="text-lg font-medium text-ink">Andamento da obra</h2><p className="mt-1 text-sm text-muted">Preencha apenas as etapas iniciadas. Campos vazios não entram no cálculo.</p></div><div className="grid gap-5 tablet:grid-cols-2 desktop:grid-cols-4">{stages.map((stage, index) => <label key={stage.code} className="block rounded-lg bg-surface p-4"><span className="mb-2 block min-h-10 text-sm font-medium text-ink">{stage.name}</span><div className="flex items-center gap-2"><input className="admin-input" type="number" min="0" max="100" value={stage.progress_percent} onChange={(event) => setData('construction_stages', stages.map((row, rowIndex) => rowIndex === index ? { ...row, progress_percent: event.target.value } : row))} /><span>%</span></div></label>)}</div><div className="mt-8 grid gap-6 border-t border-line pt-6 tablet:grid-cols-[18rem_1fr] tablet:items-end"><Field label="Data prevista de conclusão" type="date" value={data.expected_delivery_date || ''} onChange={(event) => setData('expected_delivery_date', event.target.value)} />{overall == null ? <p className="text-sm text-muted">Preencha ao menos uma etapa para calcular a conclusão geral.</p> : <OverallProgressBar value={overall} completionDate={data.expected_delivery_date} />}</div></section>;
}

export default function ContentManager({ data, setData, item, showPlans = true, showStages = true }) {
    const media = item?.media_assets || [];
    const removed = data.remove_media_ids || [];
    const visibleMedia = media.filter((asset) => !removed.includes(asset.id));
    return <>
        <section className="grid gap-5 rounded-xl border border-line bg-white p-6 shadow-sm tablet:grid-cols-2"><div className="tablet:col-span-2"><h2 className="text-lg font-medium text-ink">Imagens das seções</h2><p className="mt-1 text-sm text-muted">Imagens independentes da capa e da galeria.</p></div>{[['about_image', 'Imagem de Sobre', item?.about_media], ['promotion_image', 'Imagem promocional', item?.promotion_media]].map(([key, label, current]) => <label key={key}><span className="admin-label">{label}</span>{current?.url && <img src={current.url} alt="" className="mb-3 aspect-video w-full rounded-lg object-cover" />}<input type="file" accept="image/jpeg,image/png,image/webp" onChange={(event) => setData(key, event.target.files?.[0] || null)} className="admin-input" /></label>)}</section>
        <section className="rounded-xl border border-line bg-white p-6 shadow-sm"><h2 className="text-lg font-medium text-ink">Galeria e imagem de capa</h2><p className="mt-1 text-sm text-muted">A imagem marcada como capa aparece nos cards e no hero.</p><input type="file" multiple accept="image/jpeg,image/png,image/webp" onChange={(event) => setData('gallery_images', Array.from(event.target.files || []))} className="mt-5 block w-full rounded-lg border border-line bg-surface p-3 text-sm" />{visibleMedia.length > 0 && <div className="mt-5 grid gap-4 tablet:grid-cols-3 desktop:grid-cols-4">{visibleMedia.map((asset) => <article key={asset.id} className="overflow-hidden rounded-xl border border-line"><img src={asset.url} alt={asset.alt_text || ''} className="aspect-[4/3] w-full object-cover" /><div className="space-y-2 p-3 text-xs"><label className="flex gap-2"><input type="radio" checked={String(data.featured_media_id || '') === String(asset.id)} onChange={() => setData('featured_media_id', asset.id)} /> Capa</label><button type="button" className="text-red-700" onClick={() => setData('remove_media_ids', [...removed, asset.id])}>Remover</button></div></article>)}</div>}</section>
        {showPlans && <Repeater title="Plantas" rows={data.floor_plans || []} onChange={(rows) => setData('floor_plans', rows)} blank={blankPlan} render={(row, index, update) => <div className="grid gap-4 tablet:grid-cols-2 desktop:grid-cols-4"><Field label="Nome" value={row.name} onChange={(e) => update(index, 'name', e.target.value)} /><Field label="Área (m²)" type="number" value={row.area || ''} onChange={(e) => update(index, 'area', e.target.value)} />{[['bedrooms', 'Quartos'], ['suites', 'Suítes'], ['bathrooms', 'Banheiros'], ['parking_spaces', 'Vagas']].map(([key, label]) => <Field key={key} label={label} type="number" value={row[key] || ''} onChange={(e) => update(index, key, e.target.value)} />)}<Field label="Link/arquivo externo" type="url" value={row.external_url || ''} onChange={(e) => update(index, 'external_url', e.target.value)} /><label><span className="admin-label">Imagem da galeria</span><select className="admin-input" value={row.media_asset_id || ''} onChange={(e) => update(index, 'media_asset_id', e.target.value)}><option value="">Sem imagem</option>{visibleMedia.map((asset) => <option key={asset.id} value={asset.id}>{asset.original_name || `Mídia ${asset.id}`}</option>)}</select></label><Field label="Descrição" as="textarea" value={row.description || ''} onChange={(e) => update(index, 'description', e.target.value)} /></div>} />}
        {showStages && <ConstructionStageGrid data={data} setData={setData} />}
        <Repeater title="Documentos e downloads" rows={data.documents || []} onChange={(rows) => setData('documents', rows)} blank={{ title: '', kind: '', external_url: '', media_asset_id: '', file: null, is_public: true }} render={(row, index, update) => <div className="grid gap-4 tablet:grid-cols-2"><Field label="Título" value={row.title} onChange={(e) => update(index, 'title', e.target.value)} /><Field label="Tipo" value={row.kind || ''} onChange={(e) => update(index, 'kind', e.target.value)} /><Field label="Link externo" type="url" value={row.external_url || ''} onChange={(e) => update(index, 'external_url', e.target.value)} /><label><span className="admin-label">Arquivo</span><input className="admin-input" type="file" onChange={(e) => update(index, 'file', e.target.files?.[0] || null)} /></label><label className="flex items-center gap-2"><input type="checkbox" checked={row.is_public !== false} onChange={(e) => update(index, 'is_public', e.target.checked)} /> Exibir no site</label></div>} />
        <Repeater title="Perguntas frequentes" rows={data.faqs || []} onChange={(rows) => setData('faqs', rows)} blank={{ question: '', answer: '', is_active: true }} render={(row, index, update) => <div className="grid gap-4 tablet:grid-cols-2"><Field label="Pergunta" value={row.question} onChange={(e) => update(index, 'question', e.target.value)} /><Field label="Resposta" as="textarea" value={row.answer} onChange={(e) => update(index, 'answer', e.target.value)} /><label className="flex items-center gap-2"><input type="checkbox" checked={row.is_active !== false} onChange={(e) => update(index, 'is_active', e.target.checked)} /> Exibir no site</label></div>} />
        <section className="grid gap-5 rounded-xl border border-line bg-white p-6 shadow-sm tablet:grid-cols-2"><div className="tablet:col-span-2"><h2 className="text-lg font-medium text-ink">SEO</h2></div><Field label="Título SEO" value={data.seo_title || ''} onChange={(e) => setData('seo_title', e.target.value)} /><Field label="URL canônica" type="url" value={data.seo_canonical_url || ''} onChange={(e) => setData('seo_canonical_url', e.target.value)} /><Field label="Descrição SEO" as="textarea" value={data.seo_description || ''} onChange={(e) => setData('seo_description', e.target.value)} /><Field label="Robots" value={data.seo_robots || 'index,follow'} onChange={(e) => setData('seo_robots', e.target.value)} /></section>
    </>;
}

export const contentDefaults = (item, stageDefinitions = null) => ({
    gallery_images: [], about_image: null, promotion_image: null, remove_media_ids: [], featured_media_id: item?.media_assets?.find((asset) => asset.pivot?.is_featured)?.id || '',
    floor_plans: item?.floor_plans || [], documents: item?.documents || [], construction_stages: stageDefinitions ? fixedStageDefaults(item, stageDefinitions) : (item?.construction_stages || []), faqs: item?.faqs || [],
    seo_title: item?.seo?.title || '', seo_description: item?.seo?.description || '', seo_canonical_url: item?.seo?.canonical_url || '', seo_robots: item?.seo?.robots || 'index,follow',
});
