import { Link, router } from '@inertiajs/react';
import { useState } from 'react';
import EmptyState from '../UI/EmptyState';

const purposes = { sale: 'Venda', rent: 'Locacao', sale_rent: 'Venda + Locacao', season: 'Temporada' };
const statuses = { published: ['Publicado', 'bg-emerald-50 text-emerald-700'], draft: ['Rascunho', 'bg-amber-50 text-amber-700'], archived: ['Arquivado', 'bg-gray-100 text-gray-600'] };
const money = (value) => value && Number(value) > 0 ? new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(Number(value)) : null;

function Price({ item, entityType }) {
    if (item.price_on_request) return <span className="text-xs text-muted">Sob consulta</span>;
    const purpose = item.commercial_purpose;
    const sale = money(item.sale_price || item.regular_price || item.starting_price);
    const rent = money(item.rent_price);
    if (entityType === 'property') return <div className="space-y-0.5 text-xs">{purpose !== 'rent' && sale && <span className="block">Venda: {sale}</span>}{['rent', 'sale_rent', 'season'].includes(purpose) && rent && <span className="block">Locacao: {rent} / mes</span>}{!sale && !rent && <span className="text-muted">Sob consulta</span>}</div>;
    return <span className="text-xs">{sale ? `A partir de ${sale}` : 'Sob consulta'}</span>;
}

export default function EntityTable({ items, filters = {}, filterOptions = {}, basePath, publicPath, typeLabel, entityType, typeRelation }) {
    const [form, setForm] = useState({ search: filters.search || '', type_id: filters.type_id || '', commercial_purpose: filters.commercial_purpose || '', city_id: filters.city_id || '', status: filters.status || '' });
    const [selected, setSelected] = useState([]);
    const [pendingDelete, setPendingDelete] = useState(null);
    const [deleting, setDeleting] = useState(false);
    const rows = items.data || [];
    const allSelected = rows.length > 0 && rows.every((item) => selected.includes(item.id));
    const submit = (event) => { event.preventDefault(); router.get(basePath, Object.fromEntries(Object.entries(form).filter(([, value]) => value !== '')), { preserveState: true, preserveScroll: true, replace: true }); };
    const clear = () => { setForm({ search: '', type_id: '', commercial_purpose: '', city_id: '', status: '' }); router.get(basePath, {}, { replace: true }); };
    const toggleAll = () => setSelected(allSelected ? selected.filter((id) => !rows.some((item) => item.id === id)) : [...new Set([...selected, ...rows.map((item) => item.id)])]);
    const remove = () => {
        if (!pendingDelete || deleting) return;
        setDeleting(true);
        router.delete(`${basePath}/${pendingDelete.slug}`, { preserveScroll: true, onFinish: () => { setDeleting(false); setPendingDelete(null); } });
    };

    return <div className="space-y-4"><form onSubmit={submit} className="rounded-xl border border-line bg-white p-5 shadow-sm"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-medium text-ink">Filtros</h2><p className="mt-1 text-xs text-muted">Refine a listagem sem perder o estado ao navegar.</p></div><button type="button" onClick={clear} className="text-xs font-medium uppercase text-brand">Limpar filtros</button></div><div className="grid gap-3 tablet:grid-cols-2 desktop:grid-cols-5"><label><span className="admin-label">Buscar</span><input className="admin-input" value={form.search} onChange={(event) => setForm({ ...form, search: event.target.value })} placeholder={`Buscar ${typeLabel}...`} /></label><label><span className="admin-label">Tipo</span><select className="admin-input" value={form.type_id} onChange={(event) => setForm({ ...form, type_id: event.target.value })}><option value="">Todos</option>{(filterOptions.types || []).map((option) => <option key={option.id} value={option.id}>{option.name}</option>)}</select></label><label><span className="admin-label">Finalidade</span><select className="admin-input" value={form.commercial_purpose} onChange={(event) => setForm({ ...form, commercial_purpose: event.target.value })}><option value="">Todas</option>{Object.entries(purposes).map(([id, name]) => <option key={id} value={id}>{name}</option>)}</select></label><label><span className="admin-label">Cidade</span><select className="admin-input" value={form.city_id} onChange={(event) => setForm({ ...form, city_id: event.target.value })}><option value="">Todas</option>{(filterOptions.cities || []).map((option) => <option key={option.id} value={option.id}>{option.name}</option>)}</select></label><label><span className="admin-label">Status</span><div className="flex gap-2"><select className="admin-input" value={form.status} onChange={(event) => setForm({ ...form, status: event.target.value })}><option value="">Todos</option><option value="published">Publicado</option><option value="draft">Rascunho</option><option value="archived">Arquivado</option></select><button className="rounded-lg bg-brand px-4 text-xs font-medium text-white">Filtrar</button></div></label></div></form>
        <div className="flex min-h-12 items-center justify-between rounded-xl border border-line bg-white px-5 text-sm"><span><strong>Selecionados:</strong> {selected.length}</span><span className="text-xs text-muted">Acoes em massa ficam indisponiveis sem uma operacao segura no backend.</span></div>
        {!rows.length ? <EmptyState title={`Nenhum ${typeLabel} encontrado`}>Altere ou limpe os filtros para consultar outros registros.</EmptyState> : <div className="overflow-x-auto rounded-xl border border-line bg-white shadow-sm"><table className="w-full min-w-[980px] text-left text-sm"><thead className="border-b border-line bg-surface text-[.7rem] uppercase tracking-[.05em] text-muted"><tr><th className="w-12 px-4 py-3"><input type="checkbox" checked={allSelected} onChange={toggleAll} aria-label="Selecionar todos" /></th><th className="px-3 py-3">{typeLabel}</th><th className="px-3 py-3">Tipo</th><th className="px-3 py-3">Finalidade</th><th className="px-3 py-3">Preco</th><th className="px-3 py-3">Cidade</th><th className="px-3 py-3">Status</th><th className="px-4 py-3 text-right">Acoes</th></tr></thead><tbody>{rows.map((item) => { const cover = item.media_assets?.find((asset) => asset.pivot?.is_featured) || item.media_assets?.[0]; const status = statuses[item.status] || [item.status, 'bg-gray-100 text-gray-600']; return <tr key={item.id} className="border-b border-line last:border-0"><td className="px-4 py-3"><input type="checkbox" checked={selected.includes(item.id)} onChange={() => setSelected((current) => current.includes(item.id) ? current.filter((id) => id !== item.id) : [...current, item.id])} aria-label={`Selecionar ${item.title}`} /></td><td className="px-3 py-3"><div className="flex items-center gap-3">{cover?.url ? <img src={cover.url} alt="" className="h-12 w-16 rounded-lg object-cover" /> : <div className="h-12 w-16 rounded-lg bg-surface" />}<div className="max-w-[260px]"><strong className="block truncate font-medium text-ink">{item.title}</strong><span className="mt-0.5 block truncate text-xs text-muted">{item.reference_code || item.neighborhood || item.address || 'Sem referencia'}</span></div></div></td><td className="px-3 py-3 text-xs text-muted">{item[typeRelation]?.name || '-'}</td><td className="px-3 py-3"><span className="rounded-full bg-blue-50 px-2.5 py-1 text-xs text-blue-700">{purposes[item.commercial_purpose] || 'Nao informado'}</span></td><td className="px-3 py-3"><Price item={item} entityType={entityType} /></td><td className="px-3 py-3 text-xs">{item.city?.name || '-'}</td><td className="px-3 py-3"><span className={`rounded-full px-2.5 py-1 text-xs ${status[1]}`}>{status[0]}</span></td><td className="px-4 py-3"><div className="flex justify-end gap-3 text-xs font-medium"><a href={`${publicPath}/${item.slug}`} target="_blank" rel="noreferrer" className="text-muted hover:text-brand">Visualizar</a><Link href={`${basePath}/${item.slug}/edit`} className="text-brand">Editar</Link><button type="button" onClick={() => setPendingDelete(item)} className="text-red-700">Excluir</button></div></td></tr>; })}</tbody></table></div>}
        {items.links?.length > 3 && <nav className="flex flex-wrap justify-center gap-1" aria-label="Paginacao">{items.links.map((link, index) => link.url ? <Link key={index} href={link.url} preserveState className={`rounded-lg px-3 py-2 text-xs ${link.active ? 'bg-brand text-white' : 'border border-line bg-white text-muted'}`} dangerouslySetInnerHTML={{ __html: link.label }} /> : <span key={index} className="rounded-lg border border-line px-3 py-2 text-xs text-gray-300" dangerouslySetInnerHTML={{ __html: link.label }} />)}</nav>}
        {pendingDelete && <div role="dialog" aria-modal="true" aria-labelledby="delete-title" className="fixed inset-0 z-[200] grid place-items-center bg-black/55 p-5" onMouseDown={(event) => { if (event.target === event.currentTarget) setPendingDelete(null); }}><div className="w-full max-w-md rounded-2xl bg-white p-7 shadow-2xl"><h2 id="delete-title" className="text-xl font-medium text-ink">Excluir empreendimento?</h2><p className="mt-3 text-sm leading-6 text-muted">Tem certeza de que deseja excluir “{pendingDelete.title}”? A página pública deixará de ficar disponível e esta ação não poderá ser desfeita pelo painel.</p><div className="mt-7 flex justify-end gap-3"><button type="button" onClick={() => setPendingDelete(null)} disabled={deleting} className="rounded-lg border border-line px-5 py-3 text-sm font-medium text-ink">Cancelar</button><button type="button" onClick={remove} disabled={deleting} className="rounded-lg bg-red-700 px-5 py-3 text-sm font-medium text-white disabled:opacity-60">{deleting ? 'Excluindo...' : 'Excluir empreendimento'}</button></div></div></div>}
    </div>;
}
