import { Link } from '@inertiajs/react';
import PublicLayout from '../../../Components/Layout/PublicLayout';
import SeoHead from '../../../Components/SEO/SeoHead';
import Container from '../../../Components/UI/Container';
import EmptyState from '../../../Components/UI/EmptyState';

const date = (value) => value ? new Date(value).toLocaleDateString('pt-BR', { day: '2-digit', month: 'long', year: 'numeric' }) : '';
const image = (post) => post?.featured_media?.url || '/reference-assets/blog-city.jpg';

function CompactPost({ post }) {
    return <Link href={`/blog/${post.slug}`} className="group grid grid-cols-[112px_1fr] gap-4"><div className="overflow-hidden rounded-xl"><img src={image(post)} alt="" className="aspect-square h-full w-full object-cover transition duration-500 group-hover:scale-[1.03]" /></div><div className="py-1"><time className="text-[.7rem] text-muted">{date(post.published_at)}</time><h3 className="mt-2 text-base font-normal leading-snug text-brand">{post.title}</h3>{post.excerpt && <p className="mt-2 line-clamp-2 text-xs leading-5 text-muted">{post.excerpt}</p>}</div></Link>;
}

function PostCard({ post }) {
    return <Link href={`/blog/${post.slug}`} className="group flex h-full flex-col"><div className="overflow-hidden rounded-xl"><img src={image(post)} alt="" className="aspect-[4/3] w-full object-cover transition duration-500 group-hover:scale-[1.025]" /></div><time className="mt-4 text-[.72rem] text-muted">{date(post.published_at)}</time><h3 className="mt-2 text-xl font-normal leading-tight text-brand">{post.title}</h3>{post.excerpt && <p className="mt-3 line-clamp-3 text-sm font-light leading-6 text-muted">{post.excerpt}</p>}<span className="mt-5 text-xs font-bold uppercase tracking-[.06em] text-brand">Leia mais</span></Link>;
}

export default function Index({ posts, categories = [], activeCategory = null }) {
    const [featured, ...remaining] = posts.data;
    const supporting = remaining.slice(0, 3);
    const grid = remaining.slice(3);
    const active = categories.find((category) => category.slug === activeCategory);

    return <PublicLayout headerTone="transparent"><SeoHead title={active ? `${active.name} | Blog` : 'Blog'} description="Conteudos para quem deseja morar, investir e acompanhar o mercado imobiliario." />
        <section className="relative flex min-h-[600px] items-center overflow-hidden px-5 pt-24 text-center text-white"><img src="/reference-assets/blog-people.webp" alt="" className="absolute inset-0 h-full w-full object-cover" /><div className="red-overlay absolute inset-0" /><div className="relative z-10 mx-auto max-w-[1120px]"><h1 className="text-[clamp(2.35rem,4.2vw,4rem)] font-light uppercase leading-[1.08] tracking-[-.02em]">Conteudos para quem deseja morar, investir e acompanhar o mercado imobiliario.</h1><p className="mx-auto mt-6 max-w-[900px] text-lg font-light leading-8 text-white/90">Noticias, dicas, tendencias e conteudos exclusivos sobre loteamentos, empreendimentos e investimentos imobiliarios para tomar decisoes com mais seguranca.</p></div></section>
        <nav aria-label="Categorias do blog" className="border-b border-line bg-white"><Container className="flex max-w-[1280px] gap-2 overflow-x-auto py-5 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden"><Link href="/blog" className={`shrink-0 rounded-full px-5 py-2.5 text-xs font-medium uppercase tracking-wide ${!activeCategory ? 'bg-brand text-white' : 'border border-line text-muted'}`}>Todos</Link>{categories.map((category) => <Link key={category.id} href={`/blog?category=${category.slug}`} className={`shrink-0 rounded-full px-5 py-2.5 text-xs font-medium uppercase tracking-wide ${activeCategory === category.slug ? 'bg-brand text-white' : 'border border-line text-muted hover:border-brand hover:text-brand'}`}>{category.name} <span className="opacity-60">({category.posts_count})</span></Link>)}</Container></nav>
        <Container className="max-w-[1280px] py-20">{featured ? <div className="grid items-start gap-12 desktop:grid-cols-[minmax(0,1fr)_280px]"><main><header className="mb-8"><p className="eyebrow">{active?.name || featured.categories?.[0]?.name || 'Conteudos recentes'}</p><h2 className="mt-2 text-[clamp(2.2rem,4vw,3.5rem)] font-light leading-tight text-brand">{active?.name || 'Destaques do Blog'}</h2></header><div className="grid gap-7 tablet:grid-cols-[minmax(0,1.35fr)_minmax(280px,.65fr)]"><Link href={`/blog/${featured.slug}`} className="group relative min-h-[520px] overflow-hidden rounded-xl text-white"><img src={image(featured)} alt="" className="absolute inset-0 h-full w-full object-cover transition duration-700 group-hover:scale-[1.025]" /><div className="absolute inset-0 bg-gradient-to-t from-black/85 via-black/20 to-transparent" /><div className="absolute inset-x-0 bottom-0 p-7"><span className="rounded-full bg-white px-3 py-1.5 text-[.65rem] text-ink">{featured.categories?.[0]?.name || 'Blog'}</span><p className="mt-5 text-xs text-white/75">{featured.author?.name || 'Pascoal Loteamentos'} · {date(featured.published_at)}</p><h3 className="mt-3 text-[2rem] font-normal leading-tight">{featured.title}</h3>{featured.excerpt && <p className="mt-3 line-clamp-3 text-sm leading-6 text-white/80">{featured.excerpt}</p>}</div></Link><div className="space-y-7">{supporting.map((post) => <CompactPost key={post.id} post={post} />)}</div></div>{grid.length > 0 && <section className="mt-16 border-t border-line pt-12"><h2 className="text-3xl font-light text-brand">Mais conteudos</h2><div className="mt-8 grid gap-x-7 gap-y-12 tablet:grid-cols-2 desktop:grid-cols-3">{grid.map((post) => <PostCard key={post.id} post={post} />)}</div></section>}</main><aside className="rounded-2xl bg-white p-7 shadow-[0_10px_35px_rgba(17,17,17,.06)]"><h2 className="text-2xl font-light text-brand">Categorias</h2><div className="mt-5 space-y-3">{categories.map((category) => <Link key={category.id} href={`/blog?category=${category.slug}`} className={`flex justify-between text-sm ${activeCategory === category.slug ? 'font-medium text-brand' : 'text-muted hover:text-brand'}`}><span>{category.name}</span><span>{category.posts_count}</span></Link>)}</div><div className="mt-10 border-t border-line pt-8"><h2 className="text-xl font-light text-brand">Acompanhe nossos conteudos</h2><p className="mt-3 text-sm font-light leading-6 text-muted">Veja novidades, dicas e oportunidades tambem em nossas redes sociais.</p><Link href="/contato" className="brand-button mt-5 inline-flex">Fale conosco</Link></div></aside></div> : <EmptyState>Os artigos serao publicados em breve.</EmptyState>}</Container>
    </PublicLayout>;
}
