import { Link } from '@inertiajs/react';
import PublicLayout from '../../../Components/Layout/PublicLayout';
import SeoHead from '../../../Components/SEO/SeoHead';
import Container from '../../../Components/UI/Container';
import SocialIcon from '../../../Components/UI/SocialIcon';

const date = (value) => value ? new Date(value).toLocaleDateString('pt-BR', { day: '2-digit', month: 'long', year: 'numeric' }) : '';

export default function Show({ post, related = [] }) {
    const cover = post.featured_media?.url || '/reference-assets/blog-city.jpg';
    const share = typeof window === 'undefined' ? '' : encodeURIComponent(window.location.href);
    return <PublicLayout headerTone="light"><SeoHead title={post.seo?.title || post.title} description={post.seo?.description || post.excerpt} />
        <header className="bg-surface px-5 pb-40 pt-44 text-center tablet:pb-[248px] tablet:pt-52"><div className="mx-auto max-w-[980px]"><p className="text-xs font-medium uppercase tracking-[.14em] text-brand">{post.categories?.[0]?.name || 'Mercado imobiliario'}</p><h1 className="mt-5 text-[clamp(2.4rem,5vw,4.75rem)] font-light leading-[1.05] tracking-[-.03em] text-ink">{post.title}</h1>{post.excerpt && <p className="mx-auto mt-7 max-w-[780px] text-lg font-light leading-8 text-muted">{post.excerpt}</p>}<p className="mt-7 text-xs uppercase tracking-[.08em] text-muted">{post.author?.name || 'Pascoal Loteamentos'} · {date(post.published_at)}</p></div></header>
        <Container className="max-w-[1280px] pb-[var(--section-space)]"><img src={cover} alt={post.title} className="mx-auto -mt-28 aspect-[16/8] w-full max-w-[1120px] rounded-2xl object-cover tablet:-mt-40" /><div className="mx-auto mt-16 grid max-w-[1120px] items-start gap-14 desktop:grid-cols-[minmax(0,820px)_240px]"><article className="rich-public-content text-[17px] font-light leading-[1.75] text-muted" dangerouslySetInnerHTML={{ __html: post.content }} /><aside className="space-y-8 desktop:sticky desktop:top-32"><div><h2 className="text-xl font-light text-brand">Compartilhe</h2><div className="mt-4 flex gap-2"><a href={`https://www.facebook.com/sharer/sharer.php?u=${share}`} target="_blank" rel="noopener noreferrer" aria-label="Compartilhar no Facebook" title="Compartilhar no Facebook" className="grid size-10 place-items-center rounded-full bg-brand text-white transition hover:bg-brand-dark focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-brand/30"><SocialIcon network="facebook" /></a><a href={`https://www.linkedin.com/sharing/share-offsite/?url=${share}`} target="_blank" rel="noopener noreferrer" aria-label="Compartilhar no LinkedIn" title="Compartilhar no LinkedIn" className="grid size-10 place-items-center rounded-full bg-brand text-white transition hover:bg-brand-dark focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-brand/30"><SocialIcon network="linkedin" /></a><a href={`https://wa.me/?text=${share}`} target="_blank" rel="noopener noreferrer" aria-label="Compartilhar no WhatsApp" title="Compartilhar no WhatsApp" className="grid size-10 place-items-center rounded-full bg-brand text-white transition hover:bg-brand-dark focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-brand/30"><SocialIcon network="whatsapp" /></a></div></div><div className="border-t border-line pt-7"><h2 className="text-xl font-light text-brand">Categorias</h2><div className="mt-4 space-y-2">{post.categories?.map((category) => <Link key={category.id} href={`/blog?category=${category.slug}`} className="block text-sm text-muted hover:text-brand">{category.name}</Link>)}</div></div></aside></div>
        {related.length > 0 && <section className="mx-auto mt-20 max-w-[1120px] border-t border-line pt-12"><p className="eyebrow">Continue lendo</p><h2 className="section-title mt-2">Conteudos relacionados</h2><div className="mt-8 grid gap-7 tablet:grid-cols-2 desktop:grid-cols-3">{related.map((item) => <Link key={item.id} href={`/blog/${item.slug}`} className="group"><div className="overflow-hidden rounded-xl"><img src={item.featured_media?.url || '/reference-assets/blog-city.jpg'} alt="" className="aspect-[4/3] w-full object-cover transition duration-500 group-hover:scale-[1.025]" /></div><p className="mt-4 text-xs text-muted">{date(item.published_at)}</p><h3 className="mt-2 text-xl font-normal leading-tight text-brand">{item.title}</h3><span className="mt-5 block text-xs font-bold uppercase text-brand">Leia mais</span></Link>)}</div></section>}
        </Container></PublicLayout>;
}
